name: generator
description: "A simple generator project."
version: 0.0.1
homepage:
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build:  
  source_gen:  
  graphs: 2.2.0
  annotation:
    path: ../annotation
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:  

flutter:
